module.exports = {
  title: 'Frontend-notes',
  description: '记录前端点滴，构造前端知识体系',
  base: '/frontend-notes/',
  themeConfig: {
    sidebarDepth: 2,
    lastUpdated: 'Last Updated',
    nav: [
      { text: '算法练习', link: 'https://xinpuchen.github.io/awesome-coding/' },
      { text: '博客', link: 'https://xinpuchen.github.io' },
      { text: 'github', link: 'https://github.com/xinpuchen' },
    ],
    sidebar: [
      {
        title: 'HTML',
        children: [
          'HTML/标准模式与混杂模式.md',
          'HTML/块与行内元素.md',
          'HTML/小知识点.md',
          'HTML/重排-重绘.md',
          'HTML/BOM对象.md',
          'HTML/DOM操作为什么耗时.md',
          'HTML/DOM优化.md',
          'HTML/HTML5新标准.md',
          'HTML/meta标签的作用.md',
          'HTML/script标签defer与async.md',
        ],
      },
      {
        title: 'CSS',
        children: [
          'CSS/BFC-IFC.md',
          'CSS/CSS3新标准.md',
          'CSS/box-sizing.md',
          'CSS/display.md',
          'CSS/div水平垂直居中方法.md',
          'CSS/flex布局.md',
          'CSS/link与@import的区别.md',
          'CSS/position详解.md',
          'CSS/transition和animate的区别.md',
          'CSS/transition实现类轮播图方法.md',
          'CSS/translate-transform-transition.md',
          'CSS/三栏布局-中间自适应.md',
          'CSS/优雅降级与渐进增强.md',
          'CSS/伪类-伪元素.md',
          'CSS/保持宽高比例.md',
          'CSS/圆环进度条实现.md',
          'CSS/媒体查询.md',
          'CSS/小知识点.md',
          'CSS/斑马表格原生实现.md',
          'CSS/浮动清除方法.md',
          'CSS/移动端屏幕尺寸适配方案.md',
          'CSS/长度单位小结.md',
          'CSS/隐藏页面元素的五种方法.md',
        ],
      },
      {
        title: 'JavaScript',
        children: [
          'JavaScript/Ajax.md',
          'JavaScript/ES6新语法.md',
          'JavaScript/ES7装饰器.md',
          'JavaScript/JQuery部分.md',
          'JavaScript/JS严格模式.md',
          'JavaScript/JS实现发布订阅-class-event.md',
          'JavaScript/JS实现异步.md',
          'JavaScript/JS实现继承.md',
          'JavaScript/JS模块化规范..md',
          'JavaScript/JS深浅拷贝.md',
          'JavaScript/JS链式调用.md',
          'JavaScript/LazyMan.md',
          'JavaScript/Object.defineProperty.md',
          'JavaScript/canvas/知识点.md',
          'JavaScript/event-loop/事件传递机制.md',
          'JavaScript/event-loop/事件委托-事件代理.md',
          'JavaScript/js文件上传.md',
          'JavaScript/new的作用.md',
          'JavaScript/promise/Promise.md',
          'JavaScript/promise/使用Promise封装Ajax.md',
          'JavaScript/typeof.md',
          'JavaScript/作用域/从ECMAScript规范解读this.md',
          'JavaScript/作用域/作用域.md',
          'JavaScript/作用域/作用域链.md',
          'JavaScript/作用域/执行上下文栈.md',
          'JavaScript/内存泄漏.md',
          'JavaScript/原型/JS原型链.md',
          'JavaScript/变量对象.md',
          'JavaScript/小知识点.md',
          'JavaScript/常见字符串处理.md',
          'JavaScript/执行上下文.md',
          'JavaScript/数组的原生方法.md',
          'JavaScript/正则对象原生方法.md',
          'JavaScript/特殊实例/2D平扫全景的H5实现.md',
          'JavaScript/特殊实例/JS实现图片懒加载.md',
          'JavaScript/特殊实例/JS实现持续动画.md',
          'JavaScript/特殊实例/insertAfter方法的实现.md',
          'JavaScript/特殊实例/木桶布局.md',
          'JavaScript/监听数组变化.md',
          'JavaScript/箭头函数.md',
          'JavaScript/遍历.md',
        ],
      },
      {
        title: '浏览器',
        children: [
          '浏览器/HTTP/HTTP1.0-1.1-2.md',
          '浏览器/HTTP/HTTPS.md',
          '浏览器/HTTP/HTTP响应头.md',
          '浏览器/HTTP/HTTP状态码总结.md',
          '浏览器/HTTP/HTTP请求方法及其比较.md',
          '浏览器/主流浏览器及内核.md',
          '浏览器/关于浏览器存储的讨论与实践.md',
          '浏览器/前端性能优化.md',
          '浏览器/前端渲染VS后端渲染.md',
          '浏览器/浏览器安全.md',
          '浏览器/浏览器缓存.md',
          '浏览器/浏览器页面渲染过程.md',
          '浏览器/白屏问题和FOUC.md',
          '浏览器/跨域总结/cors.md',
          '浏览器/跨域总结/跨站请求伪造和SameSite.md',
          '浏览器/输入URL到页面加载全过程.md',
          '浏览器/重绘-Repaint和回流-Reflow.md',
        ],
      },
      {
        title: '前端框架',
        children: [
          '前端框架/MVC-MVVM.md',
          '前端框架/React/Flux-Redux演变历程.md',
          '前端框架/React/React-Diff算法.md',
          '前端框架/React/React-Router-History详解.md',
          '前端框架/React/React-setState详解.md',
          '前端框架/React/React-高阶组件.md',
          '前端框架/React/React生命周期.md',
          '前端框架/React/React面试题.md',
          '前端框架/React/Redux中间件.md',
          '前端框架/React/Ref操作DOM.md',
          '前端框架/Vue/Vue-router原理.md',
          '前端框架/Vue/Vuex包括什么.md',
          '前端框架/Vue/Vue中的数据劫持.md',
          '前端框架/Vue/Vue的生命周期.md',
          '前端框架/Vue/Vue相对原生JS的优点.md',
          '前端框架/Vue/双向绑定.md',
          '前端框架/Vue/小知识点.md',
          '前端框架/Vue/组件通信方法.md',
          '前端框架/Vue与React的区别.md',
          '前端框架/diff算法.md',
          '前端框架/virtual-dom简析.md',
          '前端框架/前端路由与后端路由.md',
          '前端框架/小程序/小程序的原理.md',
          '前端框架/技术选型.md',
          '前端框架/数据绑定.md',
          '前端框架/框架小知识点.md',
        ],
      },
      {
        title: '前端工程化',
        children: [
          '前端工程化/打包工具/webpack入门.md',
          '前端工程化/打包工具/wepack-loader-plugin.md',
          '前端工程化/测试/前端构建工具优缺点.md',
          '前端工程化/测试/前端构建：3 类 13 种热门工具的选型参考.md',
          '前端工程化/测试/测试金字塔.md',
          '前端工程化/缓存/Redis.md',
        ],
      },
      {
        title: '计算机网络',
        children: [
          '计算机网络/CDN原理.md',
          '计算机网络/TCP-IP与子网掩码.md',
          '计算机网络/TCP-拥塞控制.md',
          '计算机网络/TCP与UDP的区别.md',
          '计算机网络/TLS.md',
          '计算机网络/七层模型.md',
          '计算机网络/三次握手四次挥手.md',
        ],
      },
    ],
  },
};
