module.exports = {
  title: 'Frontend-notes',
  description: '记录知识点滴，构建完整知识体系',
  base: '/frontend-notes/',
  head: [
    [
      'link',
      { rel: 'shortcut icon', href: '/favicon.ico', type: 'image/x-icon' },
    ],
  ],
  themeConfig: {
    sidebarDepth: 0,
    lastUpdated: 'Last Updated',
    nav: [
      { text: '算法练习', link: 'https://xinpuchen.github.io/awesome-coding/' },
      { text: '博客', link: 'https://xinpuchen.github.io' },
      { text: 'github', link: 'https://github.com/xinpuchen/frontend-notes' },
    ],
    sidebar: [
      {
        title: 'HTML',
        children: [
          'HTML/标准模式与混杂模式.md',
          'HTML/HTML5新标准.md',
          'HTML/HTML5与HTML4的区别.md',
          'HTML/meta标签的作用.md',
          'HTML/行内元素与块级元素.md',
          'HTML/src和href的区别.md',
          'HTML/script标签defer与async.md',
          'HTML/BOM对象.md',
          'HTML/DOM优化.md',
          'HTML/重排与重绘.md',
          'HTML/DOM操作为什么耗时.md',
          'HTML/小知识点.md',
        ],
      },
      {
        title: 'CSS',
        children: [
          'CSS/盒模型.md',
          'CSS/BFC与IFC.md',
          'CSS/长度单位小结.md',
          'CSS/伪类-伪元素.md',
          'CSS/position详解.md',
          'CSS/浮动清除方法.md',
          'CSS/link与@import的区别.md',
          'CSS/隐藏页面元素的五种方法.md',
          'CSS/优雅降级与渐进增强.md',
          'CSS/div水平垂直居中方法.md',
          'CSS/保持宽高比例.md',
          'CSS/三栏布局-中间自适应.md',
          'CSS/flex详解.md',
          'CSS/CSS3新标准.md',
          'CSS/transition和animate的区别.md',
          'CSS/translate-transform-transition的区别.md',
          'CSS/媒体查询.md',
          'CSS/移动端屏幕尺寸适配方案.md',
          'CSS/小知识点.md',
          {
            title: '特殊实例',
            children: [
              'CSS/特殊实例/斑马表格.md',
              'CSS/特殊实例/圆环进度条.md',
              'CSS/特殊实例/品字布局.md',
              'CSS/特殊实例/圣杯布局.md',
              'CSS/特殊实例/transition实现轮播图.md',
            ],
          },
        ],
      },
      {
        title: 'JavaScript',
        children: [
          {
            title: '执行上下文',
            children: [
              'JavaScript/执行上下文/作用域.md',
              'JavaScript/执行上下文/执行上下文栈.md',
              'JavaScript/执行上下文/变量对象.md',
              'JavaScript/执行上下文/作用域链.md',
              'JavaScript/执行上下文/从ECMAScript规范解读this.md',
            ],
          },
          'JavaScript/JS原型链.md',
          'JavaScript/Ajax详解.md',
          'JavaScript/常见字符串处理.md',
          'JavaScript/数组的原生方法.md',
          'JavaScript/正则对象原生方法.md',
          'JavaScript/遍历的几种方式.md',
          'JavaScript/new的作用.md',
          'JavaScript/typeof详解.md',
          'JavaScript/Object.defineProperty详解.md',
          'JavaScript/浏览器中的事件循环机制.md',
          'JavaScript/内存泄漏.md',
          'JavaScript/JS深浅拷贝.md',
          'JavaScript/ES6新语法.md',
          'JavaScript/ES7装饰器.md',
          'JavaScript/箭头函数.md',
          'JavaScript/JS严格模式.md',
          'JavaScript/JS实现继承.md',
          'JavaScript/JS模块化规范.md',
          'JavaScript/JS链式调用.md',
          'JavaScript/监听数组变化.md',
          'JavaScript/事件传递机制.md',
          'JavaScript/事件委托.md',
          'JavaScript/JS实现发布订阅.md',
          'JavaScript/小知识点.md',
          {
            title: '特殊实例',
            children: [
              'JavaScript/特殊实例/2D平扫全景的H5实现.md',
              'JavaScript/特殊实例/JS实现持续动画.md',
              'JavaScript/特殊实例/JS实现计时器.md',
              'JavaScript/特殊实例/insertAfter方法的实现.md',
              'JavaScript/特殊实例/拖拽效果的实现.md',
              'JavaScript/特殊实例/模拟实现右键点击.md',
              'JavaScript/特殊实例/纠正js倒计时不准.md',
              'JavaScript/特殊实例/实现LazyMan.md',
              'JavaScript/特殊实例/实现表格排序.md',
              'JavaScript/特殊实例/自动搜索完成控件.md',
              'JavaScript/特殊实例/文件上传.md',
            ],
          },
        ],
      },
      {
        title: '计算机网络',
        children: [
          '计算机网络/七层模型.md',
          '计算机网络/TCP与UDP的区别.md',
          '计算机网络/TCP-IP与子网掩码.md',
          '计算机网络/TCP三次握手四次挥手.md',
          '计算机网络/TCP拥塞控制.md',
          '计算机网络/TLS解析.md',
          '计算机网络/CDN原理.md',
        ],
      },
      {
        title: '浏览器',
        children: [
          {
            title: 'HTTP',
            children: [
              '浏览器/HTTP/HTTP版本.md',
              '浏览器/HTTP/HTTP请求方法.md',
              '浏览器/HTTP/HTTP状态码.md',
              '浏览器/HTTP/HTTPS解析.md',
            ],
          },
          '浏览器/主流浏览器及内核.md',
          '浏览器/关于浏览器存储的讨论与实践.md',
          '浏览器/前端渲染VS后端渲染.md',
          '浏览器/白屏问题和FOUC.md',
          '浏览器/精准时间获取.md',
          '浏览器/浏览器缓存.md',
          '浏览器/前端性能优化.md',
          '浏览器/浏览器页面渲染过程.md',
          '浏览器/重绘和回流.md',
          '浏览器/输入URL到页面加载全过程.md',
          '浏览器/跨域总结/跨域总结.md',
          '浏览器/跨域总结/跨站请求伪造和SameSite.md',
          '浏览器/浏览器安全.md',
        ],
      },
      {
        title: '前端框架',
        children: [
          '前端框架/前端框架演进.md',
          '前端框架/MVC与MVVM.md',
          '前端框架/技术选型.md',
          '前端框架/数据绑定.md',
          '前端框架/virtual-dom解析.md',
          '前端框架/diff算法.md',
          '前端框架/前端路由与后端路由.md',
          '前端框架/Vue与React的区别.md',
          {
            title: 'React',
            children: [
              '前端框架/React/Flux-Redux演变历程.md',
              '前端框架/React/React生命周期.md',
              '前端框架/React/React-setState详解.md',
              '前端框架/React/Ref操作DOM.md',
              '前端框架/React/React-高阶组件.md',
              '前端框架/React/React常见问题.md',
              '前端框架/React/Redux中间件.md',
              '前端框架/React/React-Router-History详解.md',
            ],
          },
          {
            title: 'Vue',
            children: [
              '前端框架/Vue/Vue相对原生JS的优点.md',
              '前端框架/Vue/Vue的生命周期.md',
              '前端框架/Vue/Vue组件间通信.md',
              '前端框架/Vue/Vue中的数据劫持.md',
              '前端框架/Vue/双向绑定.md',
              '前端框架/Vue/Vue-router原理.md',
              '前端框架/Vue/Vue小知识点.md',
              '前端框架/Vue/Vuex简析.md',
            ],
          },
          {
            title: '小程序',
            children: ['前端框架/小程序/小程序的原理.md'],
          },
        ],
      },
      {
        title: '前端工程化',
        children: [
          {
            title: '测试',
            children: ['前端工程化/测试/测试金字塔.md'],
          },
          {
            title: '构建',
            children: [
              '前端工程化/构建/前端构建工具选型.md',
              '前端工程化/构建/前端构建工具优缺点.md',
              '前端工程化/构建/webpack入门.md',
              '前端工程化/构建/wepack-loader-plugin解析.md',
            ],
          },
          {
            title: '缓存',
            children: ['前端工程化/缓存/Redis缓存常见问题.md'],
          },
          {
            title: '监控',
            children: ['前端工程化/监控/错误监控原理.md'],
          },
        ],
      },
    ],
  },
};
